### ISSUE TITLE
connectionString := fmt.Sprintf("postgres://%s:%s@%s?sslmode=%s", user, password, dbname, sslmode)

### ISSUE THREAD

**Issue by DevJoseWeb** [AmundsenJunior/rest-go-mux-pq#1]
package main

import(
    "os"
    "database/sql"
    _ "github.com/lib/pq"
)

const (
    user        = os.Getenv("DB_USER"),
    password    = os.Getenv("DB_PASS"),
    dbname      = os.Getenv("DB_NAME"),
    host        = os.Getenv("DB_HOST"),
    port        = os.Getenv("DB_PORT"),
)

dsn := fmt.Sprintf("user=%s password=%s dbname=%s host=%s port=%s", user,
password, dbname, host, port)

db, err := sql.Open("postgres", dsn)

if err != nil {
    panic(err)
}

defer db.Close()

err = db.Ping()

if err != nil {
    panic(err)
}

fmt.Println("Connection established")

**Comment by AmundsenJunior** [comment]
consts can't be set by env vars directly, but thanks for the connection config change suggestions. I'll have an update soon with the changed set of env vars, the dsn formatting, deferring the db.Close() (can't believe I missed that one!), and adding the db.Ping().
