### ISSUE TITLE
 go test -v

### ISSUE THREAD

**Issue by DevJoseWeb** [AmundsenJunior/rest-go-mux-pq#2]
# _/home/dev/Documentos/GO-TUDO/rest-go-mux-pq_test
./main_test.go:29:7: undefined: main
./main_test.go:81:6: undefined: main
FAIL    _/home/dev/Documentos/GO-TUDO/rest-go-mux-pq [build failed]

**Comment by AmundsenJunior** [comment]
@DevJoseWeb can you provide more context on this error message? I'm not able to reproduce.

**Comment by AmundsenJunior** [comment]
Closing, as stale/unsubstantiated.
