### ISSUE TITLE
{ "error": "pq: password authentication failed for user \"dev\"" }

### ISSUE THREAD

**Issue by DevJoseWeb** [AmundsenJunior/rest-go-mux-pq#3]
{
"error": "pq: password authentication failed for user \"dev\""
}

https://www.youtube.com/watch?v=QsuViFb6chk&feature=youtu.be

**Comment by AmundsenJunior** [comment]
That video did not have sound, if there was narration. I was not able to follow on the specific problem being reported, other than seeing that the authentication was failing.

**Comment by AmundsenJunior** [comment]
Closing, as stale/unsubstantiated.
